sudo: required
services:
    - docker

before_install:
    - docker build -t gmartinerro/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run gmartinerro/react-test npm test -- --coverage

after_success:
    - docker build -t gmartinerro/multi-client ./client
    - docker build -t gmartinerro/multi-nginx ./nginx
    - docker build -t gmartinerro/multi-api ./api
    - docker build -t gmartinerro/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push gmartinerro/multi-client
    - docker push gmartinerro/multi-nginx
    - docker push gmartinerro/multi-api
    - docker push gmartinerro/multi-worker
